replicaCount: 1

image:
  repository: easybooking/user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: kafka:9092

